#!/usr/bin/python3
def raise_exception():
    result = "Prout" + 78
